app/core/urls.py
from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views as core

app_name = 'core'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('cadastro/', core.UserCreateView.as_view(), name='cadastro'),
]

app/refeitorio/urls.py
from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views as refeitorio

app_name = 'refeitorio'

urlpatterns = [
	path('', refeitorio.Home.as_view(), name='home'),
	path('aluno/novo', refeitorio.CadastrarAluno.as_view(), name='novo-aluno'),
	path('aluno/lista', refeitorio.ListaAlunos.as_view(), name='lista-alunos'),
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # core
    path('', include('app.core.urls'), name='core'),
    path('', include('app.refeitorio.urls'), name='refeitorio')
]

app/core/models.py
from __future__ import unicode_literals

import uuid

from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import AbstractUser, Group, Permission


# CreateUpdateModel
# - - - - - - - - - - - - - - - - - - -
class CreateUpdateModel(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now=True)

    class Meta:
        abstract = True


# UUIDUser
# - - - - - - - - - - - - - - - - - - -
class UUIDUser(AbstractUser):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    groups = models.ManyToManyField(Group, blank=True, related_name="uuiduser_set", related_query_name="user")
    user_permissions = models.ManyToManyField(Permission, blank=True, related_name="uuiduser_set", related_query_name="user")

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

app/refeitorio/models.py
from django.db import models
from app.core.models import UUIDUser

class DiasDaSemana(models.Model):
	DIA = (
	(0, 'Segunda'),
	(1, 'Terça'),
	(2, 'Quarta'),
	(3, 'Quinta'),
	(4, 'Sexta')
	)
	nome = models.CharField(max_length = 255, verbose_name = 'nome')
	identificador = models.IntegerField(choices = DIA, verbose_name = 'identificador')

	def __str__(self):
		return self.nome

	class Meta:
		verbose_name = 'dia da semana'
		verbose_name_plural = 'dias da semana'

class Refeicao(models.Model):
	TIPO = (
	(0, 'Almoço'),
	(1, 'Jantar')
	)
	usuario = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'usuarios', verbose_name = 'usuário')
	dias_refeicoes = models.ManyToManyField(DiasDaSemana, related_name = 'dias', verbose_name = 'dias das refeições', blank = True)
	tipo = models.IntegerField(choices = TIPO, verbose_name = 'tipo de refeição')

	def __str__(self):
		return 'Refeições do usuário ' + self.usuario.username

	class Meta:
		verbose_name = 'refeição'
		verbose_name_plural = 'refeições'

class Checkin(models.Model):
	usuario = models.ForeignKey(UUIDUser, on_delete = models.CASCADE, related_name = 'usuario', verbose_name = 'usuário')
	check = models.IntegerField(default = 1, verbose_name = 'Check')
	data = models.DateField(auto_now_add = True)

	def __str__(self):
		return 'Checkin do usuário ' + self.usuario.username

	class Meta:
		verbose_name = 'checkin'
		verbose_name_plural = 'checkins'

app/core/forms.py
from django import forms

from . import models

class RegistrationUserForm(forms.ModelForm):
  
  class Meta:
    model = models.UUIDUser
    fields = ('first_name', 'last_name', 'username', 'email', 'password')
    labels = {
    	'first_name': 'Primeiro Nome',
    	'last_name': 'Sobrenome',
    	'username': 'Nome de Usuário',
    	'email': 'E-mail',
    	'password': 'Senha',
    }
    widgets = {
      'password': forms.PasswordInput()
    }

app/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

from django.urls import reverse_lazy

from . import models

from .forms import RegistrationUserForm

class UserCreateView(CreateView):
    model = models.UUIDUser
    template_name = 'core/cadastro.html'
    success_url = reverse_lazy('core:login')
    form_class = RegistrationUserForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.set_password(obj.password)
    	obj.save()
    	return super(UserCreateView, self).form_valid(form)

app/refeitorio/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.views import View
from app.core.models import UUIDUser
from app.refeitorio.models import *

class Home(TemplateView):
	template_name = 'base.html'

class CadastrarAluno(View):
	def get(self, request):
		return render(request, 'cadastrar_aluno.html')

	def post(self, request):
		# Criando o Usuário
		usuario = UUIDUser(username = request.POST['username'], first_name = request.POST['nome'], password = request.POST['password'])
		usuario.set_password(usuario.password)
		usuario.save()

		print(request.POST)

		# Criando a Refeição
		if 'refeicao[0]' in request.POST:
			refeicao = Refeicao(usuario = usuario, tipo = 0)
			refeicao.save()
			dias_da_semana = DiasDaSemana.objects.all()
			for dia in dias_da_semana:
				if 'dia[0]' in request.POST:
					if int(request.POST['dia[0]']) == dia.identificador:
						refeicao.dias_refeicoes.add(dia)

				elif 'dia[1]' in request.POST:
					if int(request.POST['dia[1]']) == dia.identificador:
						refeicao.dias_refeicoes.add(dia)
				elif 'dia[2]' in request.POST:
					if int(request.POST['dia[2]']) == dia.identificador:
						refeicao.dias_refeicoes.add(dia)
				elif 'dia[3]' in request.POST:
					if int(request.POST['dia[3]']) == dia.identificador:
						refeicao.dias_refeicoes.add(dia)
				elif 'dia[4]' in request.POST:
					if int(request.POST['dia[0]']) == dia.identificador:
						refeicao.dias_refeicoes.add(dia)
				else:
					pass
			refeicao.save()
			if 'refeicao[1]' in request.POST:
				refeicao2 = Refeicao(usuario = usuario, tipo = 1)
				refeicao2.save()
				dias_da_semana = DiasDaSemana.objects.all()
				for dia in dias_da_semana:
					if 'dia[0]' in request.POST:
						if int(request.POST['dia[0]']) == dia.identificador:
							refeicao2.dias_refeicoes.add(dia)
					elif 'dia[1]' in request.POST:
						if int(request.POST['dia[1]']) == dia.identificador:
							refeicao2.dias_refeicoes.add(dia)
					elif 'dia[2]' in request.POST:
						if int(request.POST['dia[2]']) == dia.identificador:
							refeicao2.dias_refeicoes.add(dia)
					elif 'dia[3]' in request.POST:
						if int(request.POST['dia[3]']) == dia.identificador:
							refeicao2.dias_refeicoes.add(dia)
					elif 'dia[4]' in request.POST:
						if int(request.POST['dia[4]']) == dia.identificador:
							refeicao2.dias_refeicoes.add(dia)
					else:
						pass
				refeicao2.save()
			else:
				pass
		elif 'refeicao[1]' in request.POST:
			refeicao2 = Refeicao(usuario = usuario, tipo = 1)
			refeicao2.save()
			dias_da_semana = DiasDaSemana.objects.all()
			for dia in dias_da_semana:
				if 'dia[0]' in request.POST:
					if int(request.POST['dia[0]']) == dia.identificador:
						refeicao2.dias_refeicoes.add(dia)
				elif 'dia[1]' in request.POST:
					if int(request.POST['dia[1]']) == dia.identificador:
						refeicao2.dias_refeicoes.add(dia)
				elif 'dia[2]' in request.POST:
					if int(request.POST['dia[2]']) == dia.identificador:
						refeicao2.dias_refeicoes.add(dia)
				elif 'dia[3]' in request.POST:
					if int(request.POST['dia[3]']) == dia.identificador:
						refeicao2.dias_refeicoes.add(dia)
				elif 'dia[4]' in request.POST:
					if int(request.POST['dia[4]']) == dia.identificador:
						refeicao2.dias_refeicoes.add(dia)
				else:
					pass
			refeicao2.save()
		else:
			pass
		return redirect('refeitorio:home')

class ListaAlunos(View):
	def get(self, request):
		refeicoes = Refeicao.objects.all()
		return render(request, 'lista.html', {'refeicoes': refeicoes})

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Refeitorio</title>
</head>
<body>
	<h1>Refeitório do IFPB</h1>
	<ul>
		<li><a href="{% url 'refeitorio:home' %}">Home</a></li>
		{% if request.user.is_authenticated %}
		<li><a href="{% url 'refeitorio:novo-aluno' %}">Cadastrar Usuário</a></li>
		<li><a href="">Checkin</a></li>
		<li><a href="{% url 'refeitorio:lista-alunos' %}">Lista de Refeições</a></li>
		{% else %}
		<li><a href="{% url 'core:login' %}">Login</a></li>
		{% endif %}
	</ul>
	{% block content %}
	{% endblock %}
	<p>Refeitório IFPB 2018 &copy;</p>
</body>
</html>

templates/cadastrar_aluno.html
{% extends './base.html' %}

{% block content %}
<form action="{% url 'refeitorio:novo-aluno' %}" method="post">
	{% csrf_token %}
	<div>
		<label>Nome do Aluno</label><br>
		<input type="text" name="nome" placeholder="Nome do Aluno" required>
	</div>
	<br>
	<div>
		<label>Usuário de Usuário</label><br>
		<input type="text" name="username" placeholder="Nome de Usuário" required>
	</div>
	<br>
	<div>
		<label>Senha</label><br>
		<input type="password" name="password" placeholder="Senha" required>
	</div>
	<br>
	<div>
		<label>Matrícula</label>
		<br>
		<input type="text" name="matricula" placeholder="Matrícula" required>
	</div>
	<br>
	<div>
		<p>Tipo de Refeição</p>
		<input type="checkbox" name="refeicao[0]" value="0" id="almoco">
		<label for="almoco">Almoço</label>
		<input type="checkbox" name="refeicao[1]" value="1" id="jantar">
		<label for="jantar">Jantar</label>
	</div>
	<br>
	<p>Dias da/das refeição/refeições</p>
	<div>
		<input type="checkbox" name="dia[0]" value="0" id="segunda">
		<label for="segunda">Segunda-Feira</label>
		<input type="checkbox" name="dia[1]" value="1" id="terca">
		<label for="terca">Terça-Feria</label>
		<input type="checkbox" name="dia[2]" value="2" id="quarta">
		<label for="quarta">Quarta-Feria</label>
		<input type="checkbox" name="dia[3]" value="3" id="quinta">
		<label for="quinta">Quinta-Feria</label>
		<input type="checkbox" name="dia[4]" value="4" id="sexta">
		<label for="sexta">Sexta-Feria</label>
	</div>
	<br>
	<input type="submit" name="cadastrar" value="Cadastrar">
</form>
{% endblock %}

templates/core/cadastro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>Refeitório - Cadastro</title>
	<meta charset="UTF-8">
</head>
<body>
	<form method="post">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="entrar" value="entrar">
	</form>
</body>
</html>

templates/core/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>Refeitório - Login</title>
	<meta charset="UTF-8">
</head>
<body>

	<form method="post">
		{% csrf_token %}	
		{{form.as_p}}
		<input type="submit" name="entrar" value="entrar">
	</form>

</body>
</html>

templates/lista.html
{% extends './base.html' %}

{% block content %}

<div>
	<h1>Almoços</h1>
</div>

{% for refeicao in refeicoes %}
{% if refeicao.tipo == 0 %}
<p>Aluno: {{refeicao.usuario.first_name}}</p>
<p>Tipo: Almoço</p>
<p>Dias: </p>
<ul>
	{% for dia in refeicao.dias_refeicao.all %}
	<li>{{dia.nome}}</li>
	{% endfor %}
</ul>
{% else %}
<p>Aluno: {{refeicao.usuario.first_name}}</p>
<p>Tipo: Jantar</p>
<p>Dias:{{refeicao.dias_refeicoes.all}} </p>
<ul>
	{% for dia in refeicao.dias_refeicoes.all %}
	<li>{{dia.nome}}</li>
	{% endfor %}
</ul>
{% endif %}
{% endfor %}

{% endblock %}